# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
default_twitter: &default_twitter
  twitter_api_key: 'jHRFU8K9rwMeJocDxqPAwnDc4'
  twitter_api_secret: 'oYHk4RkuG0iZTnNsMHEqqNrgWLOlXolimBkJjMaKQzrP9UZeI2'

development:
  secret_key_base: 1d878160d862c9fee4c0c04afbec1b29bd9f3975595a95a22c7b5a0d4ef7151cb87c8d777477458973b3fb88c352fc361f0bc4ac3755e1ee6e6b04d013a8022d
  <<: *default_twitter

test:
  secret_key_base: aa81edc01ae60c405495cee720faeafc54b6351d4206e4d4d8de2a387cdf88fb7d248a9478e3a4a9dd885da90a102529eb408af9eddfba215b81c0ebe97ae3da
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 83d81bc30234532258791418e430a9a2a84260ea6caf85672c03dfc27b4c3a7b84f783c9d04d759b888797c681843231eb9956dbb8a8989f18a6438af8b09a17
#secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
